# ç®€ä½“ä¸­æ–‡ Chinese (Simplified) Language é»˜è®¤é…ç½®æ–‡ä»¶
# è¯‘è€…ï¼šé‡‘ç¾¿Eilles (github.com/EillesWan)
# é€‚ç”¨æ’ä»¶ä¹‹ç‰ˆæœ¬ï¼šInteractionVisualizer 1.18.15.0
# ä½¿ç”¨æ—¶ï¼Œè¯·å°†æ’ä»¶é…ç½®ç›®å½•ä¸‹åŸâ€œconfig.ymlâ€æ›¿æ¢å³å¯

# ä½œè€…çš„è¯ï¼š
# å³ä¾¿é…ç½®æ–‡ä»¶å·²ç»è¿‡æ—¶
# åœ¨å¤§å¤šæ•°æƒ…å†µä¸‹ï¼Œä¹Ÿä¾æ—§å¯ä»¥å°†å…¶ç›´æ¥æ›¿æ¢åœ¨é…ç½®ç›®å½•ä¸­
# å› ä¸ºæ–°çš„æ’ä»¶ä¼šè‡ªåŠ¨åœ¨æ–‡ä»¶ä¸­è¡¥å…¨ç¼ºå¤±çš„é…ç½®é¡¹

# è¯·æ³¨æ„ï¼Œåç»­ç¿»è¯‘æ³¨é‡Šæ—¶è¯·åœ¨äº•å·æ ‡è¯†â€œ#â€åæ·»åŠ ç©ºæ ¼
# è¯·æ³¨æ„æ±‰è‹±æ··åˆæ—¶ï¼Œè¯·å°†è‹±æ–‡å•è¯ç”¨ç©ºæ ¼éš”å¼€ï¼Œæ±‰å­—ä¸æ•°å­—æ··åˆæ—¶çš„ç©ºæ ¼åŒç†
# éƒ¨åˆ†ä¸æ¸…æ¥šçš„å†…å®¹ï¼Œè¯·åŠ¡å¿…åœ¨æ‹¬å·ä¸­ç•™ä¸‹åŸæ–‡

Database:
  # ç©å®¶æ•°æ®çš„å­˜å‚¨ç±»å‹ï¼Œæ”¯æŒ MYSQL æˆ– SQLITE
  Type: SQLITE
  MYSQL:
    Host: localhost
    Port: 3306
    Database: InteractionVisualizer
    Username: mysql
    Password: password

Messages:
  NoPermission: "&cä½ æ²¡æœ‰ä½¿ç”¨è¯¥å‘½ä»¤çš„æƒé™ã€‚"
  Reload: "&aInteractionVisualizer æ’ä»¶é‡è½½æˆåŠŸã€‚"
  Toggle:
    Usage: "&cç”¨æ³•ï¼š/interactionvisualizer toggle <itemstand/itemdrop/hologram> <block/entry> <true/false>"
    Modes: "&cåˆ‡æ¢æ¨¡å¼ï¼šitemstand, itemdrop, hologram"
    Entries: "&cåˆ‡æ¢é¡¹ç›®ï¼š%s"
    Console: "&cè¯·æä¾›ç©å®¶åç§°å‚æ•°ï¼š/interactionvisualizer toggle <æ¨¡å¼> <block/entry> <true/false> [ç©å®¶åç§°]"
    ToggleOn: "&aå·²åˆ‡æ¢è‡³ %e %m å¼€å¯"
    ToggleOff: "&eå·²åˆ‡æ¢è‡³ %e %m å…³é—­"
    PlayerNotFound: "&cè¯¥ç©å®¶å·²ç¦»çº¿ã€‚"
    All: å…¨éƒ¨
  # ä¸‹åˆ—ç»„ä»¶ï¼ˆè¯¥æ’ä»¶çš„ç»„ä»¶ï¼‰çš„ç”¨æˆ·å‹å¥½åç§°
  ModuleName:
    hologram: å…¨æ¯åƒHolograms
    itemstand: ç‰©å“æ¶ItemStands
    itemdrop: æ‰è½ç‰©ItemDrops
  # ä¸‹åˆ—ç‰©å“ï¼ˆé¡¹ç›®é”®ï¼‰çš„ç”¨æˆ·å‹å¥½åç§°
  EntryName:
    "interactionvisualizer:crafting_table": å·¥ä½œå°
    "interactionvisualizer:crafter": åˆæˆå™¨
    "interactionvisualizer:loom": ç»‡å¸ƒæœº
    "interactionvisualizer:enchantment_table": é™„é­”å°
    "interactionvisualizer:cartography_table": åˆ¶å›¾å°
    "interactionvisualizer:anvil": é“ç §
    "interactionvisualizer:grindstone": ç ‚è½®
    "interactionvisualizer:stonecutter": åˆ‡çŸ³æœº
    "interactionvisualizer:brewing_stand": é…¿é€ å°
    "interactionvisualizer:chest": ç®±å­
    "interactionvisualizer:double_chest": å¤§ç®±å­
    "interactionvisualizer:furnace": ç†”ç‚‰
    "interactionvisualizer:blast_furnace": é«˜ç‚‰
    "interactionvisualizer:smoker": çƒŸç†ç‚‰
    "interactionvisualizer:ender_chest": æœ«å½±ç®±
    "interactionvisualizer:shulker_box": æ½œå½±ç›’
    "interactionvisualizer:dispenser": å‘å°„å™¨
    "interactionvisualizer:dropper": æŠ•æ·å™¨
    "interactionvisualizer:hopper": æ¼æ–—
    "interactionvisualizer:beacon": ä¿¡æ ‡
    "interactionvisualizer:note_block": éŸ³ç¬¦ç›’
    "interactionvisualizer:jukebox": å”±ç‰‡æœº
    "interactionvisualizer:smithing_table": é”»é€ å°
    "interactionvisualizer:bee_nest": èœ‚å·¢
    "interactionvisualizer:beehive": èœ‚ç®±
    "interactionvisualizer:lectern": è®²å°
    "interactionvisualizer:campfire": ç¯ç«
    "interactionvisualizer:soul_campfire": çµé­‚ç¯ç«
    "interactionvisualizer:spawner": åˆ·æ€ªç¬¼
    "interactionvisualizer:conduit": æµ·æ´‹æ ¸å¿ƒ
    "interactionvisualizer:banner": æ——å¸œ
    "interactionvisualizer:item": æ‰è½ç‰©
    "interactionvisualizer:villager": æ‘æ°‘
    "bookshelf:bookshelf": ä¹¦æ¶

GarbageCollector:
  # æ’ä»¶ç§»é™¤å¹¶æ¸…ç†æ— éœ€ç›‘å¬çš„æ–¹å—å®ä½“å—ï¼ˆï¼Ÿå•¥ç©æ„ï¼Ÿtile entity blocksï¼‰ä¹‹é€Ÿç‡
  # ä»¥è¿è¡Œåˆ»ä¸ºå•ä½ï¼Œå¤§çº¦ 20 åˆ»ä¸ºä¸€ç§’
  # å½“æœåŠ¡å™¨æ— æ³•å¤„ç†è¿‡å¿«çš„æ›´æ–°é€Ÿåº¦æ—¶è°ƒæ•´æ­¤æ•°æ®
  Period: 600

TileEntityUpdate:
  # è‹¥ç©å®¶ç§»é€Ÿè¶…è¿‡æŒ‡å®šå€¼ï¼Œæ’ä»¶å°†åœ¨æ›´æ–°æ–¹å—å®ä½“æ—¶å¿½ç•¥ä¹‹
  # è¯¥é€Ÿåº¦ä¸ºæ°´å¹³ç§»åŠ¨ä¹‹é€Ÿåº¦
  IgnoreMovementSpeed:
    Normal: 1.31
    Flying: 1.49
    Gliding: 1.23
  # ç©å®¶å‘¨å›´åŒºå—ä¸­ï¼Œéå†æ–¹å—å®ä½“çš„èŒƒå›´
  # å€¼ä¸ºé›¶æ—¶æ„ä¸ºä»…æœ‰ç©å®¶æ‰€å¤„ä¹‹åŒºå—ä¼šè¢«éå†åˆ°
  CheckingRange: 1

LightUpdate:
  # æ’ä»¶æ›´æ–°æ‰€éœ€æ–¹å—çš„å…‰ç…§æ°´å¹³ä¹‹é€Ÿç‡
  # ä»…å½“ LightAPI å·²å®‰è£…æ—¶å¯ç”¨è¯¥é…ç½®é¡¹
  # ä»¥è¿è¡Œåˆ»ä¸ºå•ä½ï¼Œå¤§çº¦ 20 åˆ»ä¸ºä¸€ç§’
  # å½“æœåŠ¡å™¨æ— æ³•å¤„ç†è¿‡å¿«çš„æ›´æ–°é€Ÿåº¦æ—¶è°ƒæ•´æ­¤æ•°æ®
  Period: 10

# å¯¹ä»¥ä¸‹æ–¹å—å¯ç”¨æœ¬æ’ä»¶ä¹‹åŠŸèƒ½
# è‹¥æ›´æ”¹æ­¤å¤„ï¼Œéœ€è¦é‡å¯æœåŠ¡å™¨ä»¥ç”Ÿæ•ˆ
Blocks:
  Anvil:
    Enabled: true
  Banner:
    Enabled: true
    Options:
      # ç¬¦åˆé»‘åå•ä¹‹æ——å¸œå°†ä¸ä¼šæ˜¾ç¤ºæ ‡é¢˜
      Blacklist:
        # ä»…åŒ¹é…åå­—ï¼Œå¿½ç•¥é¢œè‰²ä»£ç 
        StripColorWhenMatching: true
        # ä½¿ç”¨æ­£åˆ™è¡¨è¾¾å¼è¿›è¡Œåç§°åŒ¹é…
        # è¿™é‡Œé»˜è®¤çš„é»‘åå•æ˜¯ ä¸è¯¦æ——å¸œ
        List:
          - "Ominous Banner|block\\.minecraft\\.ominous_banner"
  Barrel:
    Enabled: true
  Beacon:
    Enabled: true
    # æ’ä»¶éå†è¯¥æ–¹å—çš„é€Ÿç‡
    # ä»¥è¿è¡Œåˆ»ä¸ºå•ä½ï¼Œå¤§çº¦ 20 åˆ»ä¸ºä¸€ç§’
    # å½“æœåŠ¡å™¨æ— æ³•å¤„ç†è¿‡å¿«çš„æ›´æ–°é€Ÿåº¦ï¼ˆæœåŠ¡å™¨æ‹‰è·¨ï¼‰ã€æˆ–å¯å¤„ç†ä¹‹é€Ÿåº¦æ›´é«˜ï¼ˆæœåŠ¡å™¨ç‰›é€¼ï¼‰æ—¶è°ƒæ•´æ­¤æ•°æ®
    CheckingPeriod: 20
    # æ‚¬æµ®å±•ç¤ºä¹‹æ–‡å­—åº”å¦‚ä½•è·Ÿéšç©å®¶
    # è¯¥é¡¹å¯ä¸ºï¼šFACE, SQUARE, CIRCLE
    PathType: FACE
  BeeHive:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BeeNest:
    Enabled: true
    CheckingPeriod: 20
    Options:
      HoneyLevelCharacter: "\u2b1b"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoCampfireColor: "&c"
      BeeCountText: "&e{Current}&6/{Max}"
  BlastFurnace:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  BrewingStand:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&6"
      NoFuelColor: "&c"
      ProgressBarLength: 10
  Campfire:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u007c"
      EmptyColor: "&7"
      FilledColor: "&e"
      ProgressBarLength: 10
  CartographyTable:
    Enabled: true
  Chest:
    Enabled: true
  Conduit:
    Enabled: true
    CheckingPeriod: 20
    PathType: CIRCLE
  CraftingTable:
    Enabled: true
  Crafter:
    Enabled: true
    CheckingPeriod: 20
  Dispenser:
    Enabled: true
  DoubleChest:
    Enabled: true
  Dropper:
    Enabled: true
  EnchantmentTable:
    Enabled: true
    Options:
      TranslatableEnchantments:
        - enchantment.damage.all
        - enchantment.damage.undead
        - enchantment.damage.arthropods
        - enchantment.knockback
        - enchantment.fire
        - enchantment.sweeping
        - enchantment.protect.all
        - enchantment.protect.fire
        - enchantment.protect.fall
        - enchantment.protect.explosion
        - enchantment.protect.projectile
        - enchantment.oxygen
        - enchantment.waterWorker
        - enchantment.waterWalker
        - enchantment.frostWalker
        - enchantment.digging
        - enchantment.untouching
        - enchantment.durability
        - enchantment.lootBonus
        - enchantment.lootBonusDigger
        - enchantment.lootBonusFishing
        - enchantment.fishingSpeed
        - enchantment.arrowDamage
        - enchantment.arrowFire
        - enchantment.arrowKnockback
        - enchantment.arrowInfinite
        - enchantment.thorns
        - enchantment.mending
        - enchantment.binding_curse
        - enchantment.vanishing_curse
        - enchantment.minecraft.sharpness
        - enchantment.minecraft.smite
        - enchantment.minecraft.bane_of_arthropods
        - enchantment.minecraft.knockback
        - enchantment.minecraft.fire_aspect
        - enchantment.minecraft.sweeping
        - enchantment.minecraft.protection
        - enchantment.minecraft.fire_protection
        - enchantment.minecraft.feather_falling
        - enchantment.minecraft.blast_protection
        - enchantment.minecraft.projectile_protection
        - enchantment.minecraft.respiration
        - enchantment.minecraft.aqua_affinity
        - enchantment.minecraft.depth_strider
        - enchantment.minecraft.frost_walker
        - enchantment.minecraft.soul_speed
        - enchantment.minecraft.efficiency
        - enchantment.minecraft.silk_touch
        - enchantment.minecraft.unbreaking
        - enchantment.minecraft.looting
        - enchantment.minecraft.fortune
        - enchantment.minecraft.luck_of_the_sea
        - enchantment.minecraft.lure
        - enchantment.minecraft.power
        - enchantment.minecraft.flame
        - enchantment.minecraft.punch
        - enchantment.minecraft.infinity
        - enchantment.minecraft.thorns
        - enchantment.minecraft.mending
        - enchantment.minecraft.binding_curse
        - enchantment.minecraft.vanishing_curse
        - enchantment.minecraft.loyalty
        - enchantment.minecraft.impaling
        - enchantment.minecraft.riptide
        - enchantment.minecraft.channeling
        - enchantment.minecraft.multishot
        - enchantment.minecraft.quick_charge
        - enchantment.minecraft.piercing
      # è‹¥å­˜åœ¨è‡ªå®šä¹‰é™„é­”ï¼Œåœ¨æ­¤å¤„æ·»åŠ 
      CustomDefinedEnchantmentNames:
        "myplugin:mycustomenchant": ä¸€å¤„è‡ªå®šä¹‰é™„é­”é¡¹
  EnderChest:
    Enabled: true
  Furnace:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  Grindstone:
    Enabled: true
  Hopper:
    Enabled: true
  JukeBox:
    Enabled: true
    CheckingPeriod: 20
    Options:
      # æ˜¯å¦æµ®ç©ºæ˜¾ç¤ºå”±ç‰‡åç§°
      ShowDiscName: true
  Lectern:
    Enabled: true
    CheckingPeriod: 20
    Options:
      Line1: "&e{Title}"
      Line2: "&7&o- {Author}"
  Loom:
    Enabled: true
  NoteBlock:
    Enabled: true
  ShulkerBox:
    Enabled: true
  SmithingTable:
    Enabled: true
  Smoker:
    Enabled: true
    CheckingPeriod: 10
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&7"
      FilledColor: "&e"
      NoFuelColor: "&c"
      ProgressBarLength: 10
      AmountPending: " &7+{Amount}"
  SoulCampfire:
    Enabled: true
    CheckingPeriod: 20
    Options:
      ProgressBarCharacter: "\u007c"
      EmptyColor: "&7"
      FilledColor: "&b"
      ProgressBarLength: 10
  Spawner:
    Enabled: true
    CheckingPeriod: 20
    PathType: FACE
    Options:
      ProgressBarCharacter: "\u258e"
      EmptyColor: "&c"
      FilledColor: "&a"
      ProgressBarLength: 10
      SpawnRange: " &f{SpawnRange}m"
  Stonecutter:
    Enabled: true

Entities:
  Item:
    Enabled: true
    Options:
      # é»‘åå•ä¸­çš„ç‰©å“å°†ä¸ä¼šæ˜¾ç¤º
      Blacklist:
        # ä»…åŒ¹é…åå­—ï¼Œå¿½ç•¥é¢œè‰²ä»£ç 
        StripColorWhenMatching: true
        # ä½¿ç”¨æ­£åˆ™è¡¨è¾¾å¼åŒ¹é…åç§°æˆ–ææ–™
        # æ¯ä¸ªç‰©å“çš„ç¬¬ä¸€ä¸ªé¡¹ç”¨äºåŒ¹é…åç§°ï¼Œç¬¬äºŒä¸ªé¡¹ç”¨äºåŒ¹é…ææ–™
        List:
          - [^ALTAR Probe.*, NETHER_STAR]
          - ["^Blacklisted Item$", *]
      RegularFormat: "{Item} &bx{Amount} &6[{Timer}&6]"
      SingularFormat: "{Item} &6[{Timer}&6]"
      ToolsFormat: "{Item} &6[{Durability}&6]"
      # è‹¥å•ä¸ªæ–¹å—ä¸­çš„ç‰©å“å®ä½“å¤šäºä»¥ä¸‹æŒ‡å®šå€¼åˆ™éšè—ä¹‹
      Cramping: 6
      # ç‰©å“æ˜¾ç¤ºçš„åˆ·æ–°é€Ÿç‡
      # ä»¥è¿è¡Œåˆ»ä¸ºå•ä½ï¼Œå¤§çº¦ 20 åˆ»ä¸ºä¸€ç§’
      # è‹¥æ­¤å€¼è¿‡ä½ï¼Œå¯èƒ½ä¼šå½±å“æ€§èƒ½ï¼ˆï¼Ÿè§‚æ„Ÿï¼ŸSetting this too low might impact performanceï¼‰
      UpdateRate: 20
      Color:
        High: "&a"
        Medium: "&e"
        Low: "&c"
  Villager:
    Enabled: true

# æœ¬æ’ä»¶å¯ç”¨çš„æ˜¾ç¤ºæ¨¡å—ï¼Œè‹¥ä¸å¯ç”¨ç›¸åº”æ¨¡å—ï¼Œåˆ™å¯¹åº”æ˜¾ç¤ºæ–¹å¼ä¸ä¼šç”Ÿæ•ˆ
# Hologram â€œå…¨æ¯åƒâ€ æ˜¯ç”¨ ç›”ç”²æ¶ è¿›è¡Œ*å…¨æ¯*å±•ç¤ºçš„æ¨¡å—
# ItemStand â€œç‰©å“æ¶â€ æ˜¯ç”¨ ç›”ç”²æ¶ æˆ– å±•ç¤ºæ¡† è¿›è¡Œå±•ç¤ºçš„æ¨¡å—
# ItemDrop â€œæ‰è½ç‰©â€ æ˜¯ç”¨ æ‰è½ç‰© è¿›è¡Œå±•ç¤ºçš„æ¨¡å—
# å‚æ•° OverridingDisabled å¯æ¥å—ä¸€ç³»åˆ—çš„é¡¹ç›®é”®ï¼ˆentry keysï¼‰
# æ— è§†ç©å®¶è§‚æ„Ÿï¼Œå¼ºåˆ¶æ€§åœ°ç¦æ­¢è¿™äº›é¡¹ç›®é”®æ‰€å¯¹åº”çš„æ˜¾ç¤ºæ–¹å¼
# é¡¹ç›®é”®ä¾‹å¦‚ï¼šâ€œinteractionvisualizer:crafting_tableâ€ï¼Œè§ä¸Šæ–¹ Message é¡¹ä¸­å®šä¹‰ä¹‹å†…å®¹ã€‚
Modules:
  ItemStand:
    Enabled: true
    OverridingDisabled: []
  ItemDrop:
    Enabled: true
    OverridingDisabled: []
  Hologram:
    Enabled: true
    OverridingDisabled: []

Settings:
  # æ˜¯å¦é»˜è®¤å¯¹ç©å®¶ç¦ç”¨ä¸€åˆ‡å†…å®¹
  DefaultDisableAll: false
  # å½“æœ‰å¼‚æ­¥è°ƒç”¨ä¹‹é—®é¢˜æ—¶ï¼Œå°†æ­¤é¡¹è®¾ç½®ä¸º true
  SendAllPacketsInSync: false
  UseHandSwingAnimation: true
  PickupAnimationPlayerYOffset: 0
  DisabledWorlds: []
  # å¯èƒ½äº§ç”Ÿæå¤§èµ„æºå¼€é”€
  # é‡è¦çš„äº‹æƒ…è¯´ä¸‰éï¼ˆä»¥ä¸‹æ˜¯åŸæ–‡ğŸ˜‹ï¼‰
  # MIGHT BE RESOURCE INTENSIVE
  # MIGHT BE RESOURCE INTENSIVE
  # MIGHT BE RESOURCE INTENSIVE
  HideIfViewObstructed: false

Options:
  # å¯ç”¨è‡ªåŠ¨è”ç½‘æ›´æ–°
  Updater: true
  DownloadLanguageFiles: true